/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TradingArena {
  export type TradingResultStruct = {
    strategyId: BigNumberish;
    pnl: BigNumberish;
    totalTrades: BigNumberish;
    winningTrades: BigNumberish;
    executionLogHash: BytesLike;
    codeHash: BytesLike;
    paramsHash: BytesLike;
    datasetVersionHash: BytesLike;
    evalWindowHash: BytesLike;
    marketDataHash: BytesLike;
    timestamp: BigNumberish;
    roundId: BigNumberish;
  };

  export type TradingResultStructOutput = [
    strategyId: bigint,
    pnl: bigint,
    totalTrades: bigint,
    winningTrades: bigint,
    executionLogHash: string,
    codeHash: string,
    paramsHash: string,
    datasetVersionHash: string,
    evalWindowHash: string,
    marketDataHash: string,
    timestamp: bigint,
    roundId: bigint
  ] & {
    strategyId: bigint;
    pnl: bigint;
    totalTrades: bigint;
    winningTrades: bigint;
    executionLogHash: string;
    codeHash: string;
    paramsHash: string;
    datasetVersionHash: string;
    evalWindowHash: string;
    marketDataHash: string;
    timestamp: bigint;
    roundId: bigint;
  };
}

export interface TradingArenaInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "currentRound"
      | "finalizeRound"
      | "getLeaderboard"
      | "getResult"
      | "resultSubmitted"
      | "results"
      | "roundParticipants"
      | "rounds"
      | "startNewRound"
      | "strategyNFT"
      | "submitResult"
      | "totalPnL"
      | "verifyResult"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ResultSubmitted"
      | "RoundFinalized"
      | "RoundStarted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "currentRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaderboard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getResult",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resultSubmitted",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "results",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "roundParticipants",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rounds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startNewRound",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "strategyNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitResult",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPnL",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyResult",
    values: [
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "currentRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLeaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getResult", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resultSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "results", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "roundParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rounds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startNewRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "strategyNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalPnL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyResult",
    data: BytesLike
  ): Result;
}

export namespace ResultSubmittedEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    strategyId: BigNumberish,
    pnl: BigNumberish
  ];
  export type OutputTuple = [roundId: bigint, strategyId: bigint, pnl: bigint];
  export interface OutputObject {
    roundId: bigint;
    strategyId: bigint;
    pnl: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoundFinalizedEvent {
  export type InputTuple = [roundId: BigNumberish];
  export type OutputTuple = [roundId: bigint];
  export interface OutputObject {
    roundId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoundStartedEvent {
  export type InputTuple = [roundId: BigNumberish, marketDataHash: BytesLike];
  export type OutputTuple = [roundId: bigint, marketDataHash: string];
  export interface OutputObject {
    roundId: bigint;
    marketDataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TradingArena extends BaseContract {
  connect(runner?: ContractRunner | null): TradingArena;
  waitForDeployment(): Promise<this>;

  interface: TradingArenaInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  currentRound: TypedContractMethod<[], [bigint], "view">;

  finalizeRound: TypedContractMethod<[], [void], "nonpayable">;

  getLeaderboard: TypedContractMethod<
    [limit: BigNumberish],
    [[bigint[], bigint[]] & { strategyIds: bigint[]; pnls: bigint[] }],
    "view"
  >;

  getResult: TypedContractMethod<
    [_roundId: BigNumberish, _strategyId: BigNumberish],
    [TradingArena.TradingResultStructOutput],
    "view"
  >;

  resultSubmitted: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  results: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint
      ] & {
        strategyId: bigint;
        pnl: bigint;
        totalTrades: bigint;
        winningTrades: bigint;
        executionLogHash: string;
        codeHash: string;
        paramsHash: string;
        datasetVersionHash: string;
        evalWindowHash: string;
        marketDataHash: string;
        timestamp: bigint;
        roundId: bigint;
      }
    ],
    "view"
  >;

  roundParticipants: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  rounds: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, boolean] & {
        startTime: bigint;
        endTime: bigint;
        marketDataHash: string;
        finalized: boolean;
      }
    ],
    "view"
  >;

  startNewRound: TypedContractMethod<
    [_marketDataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  strategyNFT: TypedContractMethod<[], [string], "view">;

  submitResult: TypedContractMethod<
    [
      _strategyId: BigNumberish,
      _pnl: BigNumberish,
      _totalTrades: BigNumberish,
      _winningTrades: BigNumberish,
      _executionLogHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  totalPnL: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  verifyResult: TypedContractMethod<
    [
      _roundId: BigNumberish,
      _strategyId: BigNumberish,
      _expectedLogHash: BytesLike,
      _expectedCodeHash: BytesLike,
      _expectedParamsHash: BytesLike,
      _expectedDatasetVersionHash: BytesLike,
      _expectedEvalWindowHash: BytesLike,
      _expectedMarketDataHash: BytesLike
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "currentRound"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "finalizeRound"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getLeaderboard"
  ): TypedContractMethod<
    [limit: BigNumberish],
    [[bigint[], bigint[]] & { strategyIds: bigint[]; pnls: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResult"
  ): TypedContractMethod<
    [_roundId: BigNumberish, _strategyId: BigNumberish],
    [TradingArena.TradingResultStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "resultSubmitted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "results"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint
      ] & {
        strategyId: bigint;
        pnl: bigint;
        totalTrades: bigint;
        winningTrades: bigint;
        executionLogHash: string;
        codeHash: string;
        paramsHash: string;
        datasetVersionHash: string;
        evalWindowHash: string;
        marketDataHash: string;
        timestamp: bigint;
        roundId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "roundParticipants"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "rounds"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, boolean] & {
        startTime: bigint;
        endTime: bigint;
        marketDataHash: string;
        finalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "startNewRound"
  ): TypedContractMethod<[_marketDataHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "strategyNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitResult"
  ): TypedContractMethod<
    [
      _strategyId: BigNumberish,
      _pnl: BigNumberish,
      _totalTrades: BigNumberish,
      _winningTrades: BigNumberish,
      _executionLogHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalPnL"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyResult"
  ): TypedContractMethod<
    [
      _roundId: BigNumberish,
      _strategyId: BigNumberish,
      _expectedLogHash: BytesLike,
      _expectedCodeHash: BytesLike,
      _expectedParamsHash: BytesLike,
      _expectedDatasetVersionHash: BytesLike,
      _expectedEvalWindowHash: BytesLike,
      _expectedMarketDataHash: BytesLike
    ],
    [boolean],
    "view"
  >;

  getEvent(
    key: "ResultSubmitted"
  ): TypedContractEvent<
    ResultSubmittedEvent.InputTuple,
    ResultSubmittedEvent.OutputTuple,
    ResultSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RoundFinalized"
  ): TypedContractEvent<
    RoundFinalizedEvent.InputTuple,
    RoundFinalizedEvent.OutputTuple,
    RoundFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "RoundStarted"
  ): TypedContractEvent<
    RoundStartedEvent.InputTuple,
    RoundStartedEvent.OutputTuple,
    RoundStartedEvent.OutputObject
  >;

  filters: {
    "ResultSubmitted(uint256,uint256,int256)": TypedContractEvent<
      ResultSubmittedEvent.InputTuple,
      ResultSubmittedEvent.OutputTuple,
      ResultSubmittedEvent.OutputObject
    >;
    ResultSubmitted: TypedContractEvent<
      ResultSubmittedEvent.InputTuple,
      ResultSubmittedEvent.OutputTuple,
      ResultSubmittedEvent.OutputObject
    >;

    "RoundFinalized(uint256)": TypedContractEvent<
      RoundFinalizedEvent.InputTuple,
      RoundFinalizedEvent.OutputTuple,
      RoundFinalizedEvent.OutputObject
    >;
    RoundFinalized: TypedContractEvent<
      RoundFinalizedEvent.InputTuple,
      RoundFinalizedEvent.OutputTuple,
      RoundFinalizedEvent.OutputObject
    >;

    "RoundStarted(uint256,bytes32)": TypedContractEvent<
      RoundStartedEvent.InputTuple,
      RoundStartedEvent.OutputTuple,
      RoundStartedEvent.OutputObject
    >;
    RoundStarted: TypedContractEvent<
      RoundStartedEvent.InputTuple,
      RoundStartedEvent.OutputTuple,
      RoundStartedEvent.OutputObject
    >;
  };
}
